### ISSUE TITLE
Will you accept big change for viewdock data structure?

### ISSUE THREAD

**Issue by SlNPacifist** [emoon/ProDBG#198]
Two days ago a guy at Upwork asked me if I can fix all issues tagged "viewdock" in ProDBG project. I checked out if I can and have a question to maintainers of this project. Will you accept changes if I change data structures a bit and then fix those problems?
Current implementation seems to be pretty hacky and is not suited well for its task. Here what I mean:

Current Viewdock data structures seem to be unobvious. When empty Workspace is created, it looks like follows:
```
Workspace 
    splits: Split 
        left: None
        right: None
        left_docks: Container 
            docks: 
            rect: Rect 
                x: 0
                y: 0
                width: 0
                height: 0
        right_docks: Container 
            docks: 
            rect: Rect 
                x: 0
                y: 0
                width: 0
                height: 0
        ratio: 0
        direction: Full
        handle: SplitHandle(0)
        rect: Rect 
            x: 0
            y: 0
            width: 0
            height: 0
    rect: Rect
        x: 0,
        y: 0,
        width: 1280,
        height: 780
    window_border: 4
    handle_counter: SplitHandle(0)
```
Though there is nothing in this workspace yet, it already contains a Split. Naturally Split should always contain two children splitted horizontally or vertically. In this example our split has "Full" direction and empty left_docks and right_docks containers to show it is not a split.

Workspace with single Dock in it looks like follows (unchanged info like Workspace.rect and  workspace.window_border is removed since they never change in following examples):
```
Workspace 
    splits: Split 
        left: None
        right: None
        left_docks: Container 
            docks: Dock 
                handle: DockHandle(0)
                plugin_name: ""
                plugin_data: None
                rect: Rect 
                    x: 0
                    y: 0
                    width: 0
                    height: 0
            rect: Rect 
                x: 0
                y: 0
                width: 1280
                height: 780
        right_docks: Container 
            docks: 
            rect: Rect 
                x: 0
                y: 0
                width: 1280
                height: 780
        ratio: 1
        direction: Horizontal
        handle: SplitHandle(0)
        rect: Rect 
            x: 0
            y: 0
            width: 1280
            height: 780
    handle_counter: SplitHandle(0)
```
Now we have horizontal split direction with ratio of 1 (which means all the space is given to left dock) and new dock is added as a left child of split.

Finally, when actual split is done, Workspace looks like
```
Workspace
    splits: Split 
        left: None
        right: None
        left_docks: Container 
            docks: Dock 
                handle: DockHandle(0)
                plugin_name: ""
                plugin_data: None
                rect: Rect 
                    x: 0
                    y: 0
                    width: 0
                    height: 0
            rect: Rect 
                x: 0
                y: 0
                width: 1280
                height: 780
        right_docks: Container 
            docks: Dock 
                handle: DockHandle(1)
                plugin_name: ""
                plugin_data: None
                rect: Rect 
                    x: 0
                    y: 0
                    width: 0
                    height: 0
            rect: Rect 
                x: 0
                y: 780
                width: 1280
                height: 0
        ratio: 0.5
        direction: Horizontal
        handle: SplitHandle(0)
        rect: Rect 
            x: 0
            y: 0
            width: 1280
            height: 780
    handle_counter: SplitHandle(1)
```
Now we have Docks in each part of split and meaningful split direction and ratio.

When new split happens, structure changes as follows:
```
Workspace 
    splits: Split 
        left: Some(SplitHandle(2))
        right: None
        left_docks: Container 
            docks: 
            rect: Rect 
                x: 0
                y: 0
                width: 1280
                height: 390
        right_docks: Container 
            docks: Dock 
                handle: DockHandle(1)
                plugin_name: ""
                plugin_data: None
                rect: Rect 
                    x: 0
                    y: 0
                    width: 0
                    height: 0
            rect: Rect 
                x: 0
                y: 390
                width: 1280
                height: 390
        ratio: 0.5
        direction: Horizontal
        handle: SplitHandle(0)
        rect: Rect 
            x: 0
            y: 0
            width: 1280
            height: 780
     Split 
        left: None
        right: None
        left_docks: Container 
            docks: Dock 
                handle: DockHandle(2)
                plugin_name: ""
                plugin_data: None
                rect: Rect 
                    x: 0
                    y: 0
                    width: 0
                    height: 0
            rect: Rect 
                x: 0
                y: 0
                width: 0
                height: 0
        right_docks: Container 
            docks: Dock 
                handle: DockHandle(0)
                plugin_name: ""
                plugin_data: None
                rect: Rect 
                    x: 0
                    y: 0
                    width: 0
                    height: 0
            rect: Rect 
                x: 0
                y: 0
                width: 1280
                height: 390
        ratio: 0.5
        direction: Vertical
        handle: SplitHandle(2)
        rect: Rect 
            x: 0
            y: 0
            width: 0
            height: 0
    handle_counter: SplitHandle(2)
```
First split's left property now points to another split. However, corresponding left_docks container is now empty.

What I don't like about this structure?

 * Split contains "special" states for several situations. Direction "Full", empty Containers, ratio of 0 or 1 and special  function to check for this states. It even says it is a hack:
 
```
pub fn no_split(&mut self, direction: Direction, dock_handle: DockHandle) -> bool {
    // hack!
    if self.direction == Direction::Full {
        self.direction = direction;
    }

    if self.is_left_zero_and_none() {
    ...
```
 * Split contains both `left` and `left_docks` properties. These are mutually exclusive: either you have child dock or another split but not both.
 
Instead I want to use structure like this. Empty workspace:
```
Workspace
    root_area: None
    rect: Rect
    window_border: 4

```

Workspace with single dock (rect and window_border are not shown):
```
Workspace
    root_area: Container
```

Workspace with two docks (single split):
```
Workspace
    root_area: Split
        direction: Horizontal(0.5)
        left: Container
        right: Container
```

Workspace with three docks:
```
Workspace
    root_area: Split
        direction: Horizontal(0.5)
        left: Split
            direction: Vertical(0.5)
            left: Container
            right: Container
        right: Container
```

And so on. In Rust these structures will look like:

```
pub struct Workspace {
    root_area: Option<Area>, // None for non-initialized Workspace
}

pub struct Container {
    // not changed
}

pub struct Split {
    pub left: Box<Area>,
    pub right: Box<Area>,
    pub direction: Direction,
    pub handle: SplitHandle,
    rect: Rect,
}

pub enum Direction {
    Horizontal(f32),
    Vertical(f32)
}

pub enum Area {
    Split(Split),
    Container(Container),
}
```

Will you accept these changes if I make a proper pull request? Or should I just try to apply more hacks to current data structure in order to make it work?

By the way, am I allowed to use tree-like structure with Box<> or Splits and Container should be kept in vectors and referenced only by their handles?
